import * as Discord from "discord.js";
import { Command, Colors } from "../../global.js";

class C extends Command {
  names = ["invite", "about", "github"];
  help = "Invite the bot to your server!";
  isGame = "n" as const;

  exec(msg: Discord.Message, _: string[], _1: Discord.Client) {
    msg.channel.send({
      embeds: [{
        color: Colors.PRIMARY,
        title: "Invite link!",
        description: `**Invite Link**: [Link](https://discord.com/api/oauth2/authorize?client_id=781939317450342470&permissions=272448&scope=bot)
**Discord Server**: [Invite](https://discord.gg/4vTPWdpjFz)
**Github**: [Link](https://github.com/cursorweb/Cycle-Bot-Game)
**Replit**: [Link](https://replit.com/@Coder100/Cycle-Bot-Game-autogenerated) [@Coder100](https://repl.it/@Coder100)
\n[**Terms of Service**](https://docs.google.com/document/d/e/2PACX-1vTpwHwEm39rR32JFBadDrkhhX5ql1wGsLCxc3U0l7cJvOAiSNZWx4DaD0LtbBnxxtxPTayhk7GaIZQm/pub) | [**Privacy Policy**](https://docs.google.com/document/d/e/2PACX-1vS5W_-EcOrl3vQstWHt0hVosuKXwWvIqT7iXaGE8zPeTIA8MmyaHXzf77qO6iOm2ArHdN6iTWvXskux/pub)`
      }]
    });
  }
}

export const c = new C();