name: 'Deploy to GHCR'

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
  push-store-image:
        runs-on: ARM64
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Login to GHCR
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}


            - name: Convert repository name to lowercase
              id: repo
              run: echo "::set-output name=repo::$(echo ${{ github.repository }} | awk '{print tolower($0)}')"

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ghcr.io/${{ steps.repo.outputs.repo }}:latest
